// USER
export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS  = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// SCREAM

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CREATE_SCREAM_REQUEST = 'CREATE_SCREAM_REQUEST';
export const CREATE_SCREAM_SUCCESS = 'CREATE_SCREAM_SUCCESS';
export const CREATE_SCREAM_FAILURE = 'CREATE_SCREAM_FAILURE';

export const GET_SCREAMS_REQUEST = 'GET_SCREAMS_REQUEST';
export const GET_SCREAMS_SUCCESS = 'GET_SCREAMS_SUCCESS';
export const GET_SCREAMS_FAILURE = 'GET_SCREAMS_FAILURE';

export const GET_SCREAM_REQUEST = 'GET_SCREAM_REQUEST';
export const GET_SCREAM_SUCCESS = 'GET_SCREAM_SUCCESS';
export const GET_SCREAM_FAILURE = 'GET_SCREAM_FAILURE';

export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const DELETE_SCREAM_REQUEST = 'DELETE_SCREAM_REQUEST';
export const DELETE_SCREAM_SUCCESS = 'DELETE_SCREAM_SUCCESS';


